server:
  port: 10088

spring:
  #=========================
  #순환참조 에러를 위한 구문
  #=========================
  main:
    allow-circular-references: true

  #=========================
  # My SQL을 위한 설정       #
  #=========================
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#  config:
#    activate:
#      on-profile: default
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect